cc_test(
    name = "test_state_machine",
    srcs = ["test_state_machine.cpp"],
    deps = [
        "//src:state_machine_lib",   # matches your cc_library name
        "@googletest//:gtest_main",
    ],
)
